=== tedi21/SisypheReview/Sisyphe/cppbase/document_schema.dtd
<!-- DTD Auteur : Teddy DIDÉ -->
<!-- DTD Projet : DataSources Generator -->
<!ELEMENT document_schema    ( Workspace )        >
<!-- IS ROOT ELEMENT -->
<!ELEMENT Workspace     ( Comments?, File* )      >
<!ELEMENT File          ( Comments?, Entity*, Relation* )>
<!ELEMENT Entity        ( Comments?, Attribute* ) >
<!ELEMENT Relation      ( Comments? )             >
<!ELEMENT Attribute     ( Comments? )             >
<!ATTLIST Workspace 
  Name    CDATA #REQUIRED
  Author  CDATA #REQUIRED
  Brief   CDATA #IMPLIED 
  Version CDATA #IMPLIED 
  Type    (File|Project) "Project"
  Option  CDATA "0"                   >
<!ATTLIST File
  Name    CDATA #REQUIRED
  Alias   CDATA #IMPLIED              >
<!ATTLIST Entity 
  Name    CDATA #REQUIRED               
  SubName CDATA #IMPLIED
  Alias   CDATA #IMPLIED
  Class (Data|Function|Enumeration) "Data">
<!ATTLIST Relation
  Name          CDATA #REQUIRED  
  Alias         CDATA #IMPLIED
  Multiplicity  CDATA #IMPLIED
  Target        CDATA #IMPLIED
  TargetREF     CDATA #IMPLIED
  Source        CDATA #IMPLIED
  SourceREF     CDATA #IMPLIED        >
<!ATTLIST Attribute
  Type (Boolean|SByte|Byte|Char|Int16|UInt16|Int32|UInt32|Int64|UInt64|Single|Double|String|Text|Time|Date|Any) "Any" 
  Name     CDATA #REQUIRED
  Alias    CDATA #IMPLIED
  Modifier CDATA ""
  Default  CDATA #IMPLIED             >
<!ELEMENT Comments ( #PCDATA )        >

=== tedi21/SisypheReview/Sisyphe/script/plugins/libwordPlg/interpreter/interpreter.wordxml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE document_schema SYSTEM "document_schema.dtd">

<document_schema>
<Workspace Author="Teddy DIDE" 
           Brief="Word Interpreter generated by gensources."
           Name="wordxml_interpreter"
           Option="0"
           Type="Project"
           Version="1.00">
    <File Name="WordXMLDocument" Alias="WordXML">
      <Entity Class="Data" Name="WordXMLDocument" Alias="WordXML"/>
      <Entity Class="Function" Name="WordXMLDocument:initialize@void">
        <Attribute Name="WordXMLDocument" Alias="WordXML"/>
      </Entity>
      <Entity Class="Function" Name="WordXMLDocument:terminate@void">
        <Attribute Name="WordXMLDocument" Alias="WordXML"/>
      </Entity>
      
      <Content Type="Example" Target="WordXMLDocument:initialize@void">
xml = new WordXML();
xml.Initialize();
      </Content>  
      
      <Content Type="Example" Target="WordXMLDocument:terminate@void">
xml.Terminate();
xml = null;
      </Content>  

    </File>
</Workspace>
</document_schema>

=== tedi21/SisypheReview/Sisyphe/cppbase/cppbase.project.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE document_schema SYSTEM "document_schema.dtd">

<document_schema>
  <Workspace Author="Teddy DIDE" 
             Brief="cppBase generated by gensources."
             Name="cppBase"
			 Option="0" 
			 Type="Project" 
			 Version="1.00">
		 
    <File Name="cppInheritance">
      <Entity Name="cppInheritance">
         <Attribute Name="idDerived" Alias="derived"/>
      </Entity>
    </File>
	
    <File Name="cppFunction">
      <Entity Name="cppFunction">
         <Attribute Name="idDecFile" Alias="cppDeclarationFile"/>
         <Attribute Name="idDefFile" Alias="cppDefinitionFile"/>
      </Entity>
      <Relation Name="FK_FUNCTION_DEC_FILE" Alias="cppDeclarationFunction"/>
      <Relation Name="FK_FUNCTION_DEF_FILE" Alias="cppDefinitionFunction"/>
    </File>
    
    <File Name="cppClass">
      <Entity Name="cppClass">
         <Attribute Name="idEncapsulationClass" Alias="encapsulationClass"/>
      </Entity>
      <Relation Name="FK_CLASS_CLASS" Alias="internClasse"/>
    </File>
    
    <File Name="debugTypeInfo">
      <Entity Name="debugTypeInfo">
         <Attribute Name="idPrimitiveType" Alias="primitiveType"/>
      </Entity>
      <Relation Name="FK_DEBUGTYPE_DEBUGTYPE" Alias="richType"/>
    </File>
  </Workspace>
</document_schema>

=== tedi21/SisypheReview/Sisyphe/script/plugins/libwordPlg/interpreter/src/exportXML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE document_schema SYSTEM "document_schema.dtd">
<document_schema>

  <Workspace Author="Teddy DIDE" Brief="Word Interpreter generated by gensources." Name="wordxml_interpreter" Option="0" Type="Project" Version="1.00">
    <File Alias="WordXML" Name="WordXMLDocument">
      <Entity Alias="WordXML" Class="Data" Name="WordXMLDocument">
        <Comments> Classe permettant d'initialiser ou libérer les objets XML.</Comments>
        <Attribute Modifier="Id Const " Name="Id" Type="UInt64"/>
      </Entity>
      <Entity Class="Function" FunctionName="initialize" Name="WordXMLDocument:initialize@void">
        <Comments> Initialise le parseur XML.</Comments>
        <Attribute Alias="WordXML" Modifier="Ref Const Contextual Static " Name="WordXMLDocument" Type="UInt64"/>
        <Attribute Modifier="Id Const " Name="Id" Type="UInt64"/>
      </Entity>
      <Entity Class="Function" FunctionName="terminate" Name="WordXMLDocument:terminate@void">
        <Comments> Libère les objets XML.</Comments>
        <Attribute Alias="WordXML" Modifier="Ref Const Contextual Static " Name="WordXMLDocument" Type="UInt64"/>
        <Attribute Modifier="Id Const " Name="Id" Type="UInt64"/>
      </Entity>
      <Relation Multiplicity="Zero-One" Name="R_WordXMLDocument:initialize@void_WordXMLDocument" Source="WordXMLDocument" SourceREF="Id" Target="WordXMLDocument:initialize@void" TargetREF="WordXMLDocument"/>
      <Relation Multiplicity="Zero-One" Name="R_WordXMLDocument:terminate@void_WordXMLDocument" Source="WordXMLDocument" SourceREF="Id" Target="WordXMLDocument:terminate@void" TargetREF="WordXMLDocument"/>
      <Content Target="WordXMLDocument:initialize@void" Type="Example">
xml = new WordXML();
xml.Initialize();
      </Content>
      <Content Target="WordXMLDocument:terminate@void" Type="Example">
xml.Terminate();
xml = null;
      </Content>
    </File>
    <File Name="libword">
      <Entity Class="Package" Name="libword">
        <Attribute Modifier="Id Const " Name="Id" Type="UInt64"/>
      </Entity>
      <Relation Multiplicity="Zero-One" Name="R_libword_WordXMLDocument" Source="WordXMLDocument" SourceREF="Id" Target="libword" TargetREF="Id"/>
    </File>
  </Workspace>

</document_schema>
